version: '3.8'

services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code/
      - node_modules:/code/node_modules

volumes:
  node_modules: